export const Users = [
    {
        id : 1,
        profilePicture: "/assets/profile pic/1.jpeg",
        username: "Prince Kumar",
    },
    {
        id : 2,
        profilePicture: "/assets/profile pic/2.jpeg",
        username: "Rakhi Thakur",
    },
    {
        id : 3,
        profilePicture: "/assets/profile pic/3.jpeg",
        username: "Nilesh Ranjan",
    },
    {
        id : 4,
        profilePicture: "/assets/profile pic/4.jpeg",
        username: "Joydev Dalai",
    },
    {
        id : 5,
        profilePicture: "/assets/profile pic/5.jpeg",
        username: "Sudipta Dhara",
    },
    {
        id : 6,
        profilePicture: "/assets/profile pic/6.jpeg",
        username: "Priyanshu Singh",
    },
    {
        id : 7,
        profilePicture: "/assets/profile pic/7.jpeg",
        username: "Akshay Kumar",
    },
    {
        id : 8,
        profilePicture: "/assets/profile pic/8.jpeg",
        username: "Vivek Singh",
    },
    {
        id : 9,
        profilePicture: "/assets/profile pic/9.jpeg",
        username: "Rajeev Kumar",
    },
    {
        id : 10,
        profilePicture: "/assets/profile pic/10.jpeg",
        username: "Monster India",
    },
]


export const Posts = [
    {
        id : 1,
        desc : "Love the way you are..!!",
        photo : "/assets/posts/1 (1).jpeg",
        date : "5 mins ago",
        userID : 1,
        like : 32,
        comment : 9,
    },
    {
        id : 2,
        photo : "/assets/posts/2 (1).jpeg",
        date : "15 mins ago",
        userID : 2,
        like : 39,
        comment : 2,
    },
    {
        id : 3,
        desc : "Love to see this again..:)",
        photo : "/assets/posts/3 (1).jpeg",
        date : "30 mins ago",
        userID : 3,
        like : 45,
        comment : 23,
    },
    {
        id : 4,
        desc : "Travelling to mumbai..",
        photo : "/assets/posts/4 (1).jpeg",
        date : "2 hours ago",
        userID : 4,
        like : 12,
        comment : 34,
    },
    {
        id : 5,
        desc : "Love the way you are..!!",
        photo : "/assets/posts/5 (1).jpeg",
        date : "5 mins ago",
        userID : 5,
        like : 45,
        comment : 31,
    },
    {
        id : 6,
        desc : "Woowwww what a Great palace..",
        photo : "/assets/posts/6 (1).jpeg",
        date : "6 hours ago",
        userID : 6,
        like : 46,
        comment : 33,
    },
    {
        id : 7,
        desc : "Love the way you are..!!",
        photo : "/assets/posts/7 (1).jpeg",
        date : "5 mins ago",
        userID : 7,
        like : 42,
        comment : 9,
    },
    {
        id : 8,
        desc : "Lovely stuff is always cool",
        photo : "/assets/posts/8 (1).jpeg",
        date : "5 mins ago",
        userID : 8,
        like : 36,
        comment : 94,
    },
    {
        id : 9,
        desc : "Love the way you are..!!",
        photo : "/assets/posts/9 (1).jpeg",
        date : " 1 dyas ago",
        userID : 9,
        like : 32,
        comment : 55,
    },
    {
        id : 10,
        desc : "Love the way you are..!!",
        photo : "/assets/posts/10 (1).jpeg",
        date : " 2 dyas ago",
        userID : 10,
        like : 32,
        comment : 9,
    },
]

